[package]
name = "pattern_substring"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "pattern_substring"
path = "src/lib.rs"

[dependencies]
